-- Migration: 001_create_subscription_audit_logs.sql
-- Feature: 001-subscription-admin
-- Date: 2026-01-30
-- Description: Create table for tracking subscription modifications by admins

CREATE TABLE IF NOT EXISTS subscription_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  admin_id UUID NOT NULL,
  admin_email TEXT NOT NULL,
  user_id UUID NOT NULL,
  user_email TEXT NOT NULL,
  previous_end_date TIMESTAMPTZ,
  new_end_date TIMESTAMPTZ NOT NULL,
  action_type TEXT NOT NULL CHECK (action_type IN ('add_1_month', 'add_1_year', 'custom_date'))
);

-- Index pour recherche par utilisateur
CREATE INDEX IF NOT EXISTS idx_subscription_audit_user_id
  ON subscription_audit_logs(user_id);

-- Index pour recherche par admin
CREATE INDEX IF NOT EXISTS idx_subscription_audit_admin_id
  ON subscription_audit_logs(admin_id);

-- Index pour tri chronologique
CREATE INDEX IF NOT EXISTS idx_subscription_audit_created_at
  ON subscription_audit_logs(created_at DESC);

COMMENT ON TABLE subscription_audit_logs IS 'Historique des modifications d''abonnement effectuées par les admins du backoffice';
COMMENT ON COLUMN subscription_audit_logs.action_type IS 'Type d''action: add_1_month, add_1_year, ou custom_date';
